### ISSUE TITLE
more granularity over what is documented and where

### ISSUE THREAD

**Issue by nsheff** [databio/lucidoc#19]
Right now, you can just choose a package and then mkdocs-databio/lucidoc will automatically document it.

In pypiper, we want to document the `PipelineManager` class, and the `NGSTk` class -- only those classes, and in separate files.

http://code.databio.org/pypiper/

would lucidoc support this? If so, maybe we just need to change the mkdocs-databio processing to allow something like:'

```
plugins:
  - databio:
      autodoc:
        build_dir: "docs/autodoc_build"
        build_list:
          - package: "pypiper"
            classes: [NGStk]
            file: ngstk.md
          - package: "pypiper"
            classes: [PipelineManager]
            file: pypiper.md
  - search
```
